// lib/data/questions/general_navigation_questions.dart

import '../models/question_model.dart';

class GeneralNavigationQuestions {
  static List<Question> getQuestions() {
    return [
      Question(
        question: "The earth's magnetic field is considered to originate from:",
        options: [
          "the earth's rotation",
          "the earth's core",
          "the earth's crust",
          "solar radiation"
        ],
        correctAnswer: 1,
        explanation: "Earth's magnetic field is generated by electric currents produced by the motion of molten iron in the outer core.",
      ),
      Question(
        question: "Magnetic variation is defined as the angle between:",
        options: [
          "true north and grid north",
          "magnetic north and grid north",
          "true north and magnetic north",
          "compass north and magnetic north"
        ],
        correctAnswer: 2,
        explanation: "Magnetic variation (or declination) is the angle between true north (geographic) and magnetic north.",
      ),
      Question(
        question: "Isogonal lines on a chart join points of equal:",
        options: [
          "deviation",
          "dip",
          "variation",
          "inclination"
        ],
        correctAnswer: 2,
        explanation: "Isogonal lines connect points with equal magnetic variation on aeronautical charts.",
      ),
      Question(
        question: "Agonic lines on a chart join points of equal:",
        options: [
          "deviation",
          "dip",
          "inclination",
          "zero variation"
        ],
        correctAnswer: 3,
        explanation: "Agonic lines are isogonals with zero variation, where true north and magnetic north align.",
      ),
      Question(
        question: "The angle between the magnetic field line and the horizontal plane at any point on the earth's surface is known as:",
        options: [
          "variation",
          "deviation",
          "inclination (dip)",
          "declination"
        ],
        correctAnswer: 2,
        explanation: "Inclination or dip is the vertical angle between the magnetic field and the horizontal plane.",
      ),
    ];
  }
}